### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Munoon** [ToxicRevolution/CSGORankMeWeb#59] opened 2018-10-28 09:21 UTC
Hi! I have a problem that i cant login! After putting my login and password it redirect me to another page and i have white screen...

**Comment by kennyLtv** [comment] 2018-10-28 12:17
Do you have your error log or any information to add? This is not enough information for us to try and resolve your issue.

**Comment by Munoon** [comment] 2018-10-28 14:37
im not rly good at it. may u say where i can find error logs?

**Comment by kennyLtv** [comment] 2018-10-28 14:53
It varies from installation to installation. I would check your PHP configuration to see where it is or perform a search on the web directory for a file name of "error_log". Without any more information, we will be unable to assist you.

**Comment by Munoon** [comment] 2018-10-28 16:03
well, im understanded were error logs but there isnt write anything. i make a vidio so u can understang what the problem.
https://streamable.com/3af8j

**Comment by kennyLtv** [comment] 2018-10-28 16:52
Yea that video doesn't help as it is a server side error. Are you certain you don't have any relevant errors in an error_log anywhere? It's generating a 500 error if you don't make sure your PHP config is set to log the errors then check for an entry in your entry log. Without the log file, it will be difficult for us to remedy your issue.

**Comment by Munoon** [comment] 2018-10-28 16:57
Look:
![image](https://user-images.githubusercontent.com/43534008/47619076-4e3f4200-dae3-11e8-89ef-a069b25386ae.png)
Maybe you may send me coppie which you checked?

**Comment by kennyLtv** [comment] 2018-10-29 12:40
Did you download from the release page or from the repository download button?

**Comment by Munoon** [comment] 2018-10-30 06:54
![image](https://user-images.githubusercontent.com/43534008/47701107-7339cf00-dc21-11e8-8e31-af2ad1444ea9.png)

**Comment by Munoon** [comment] 2018-10-30 07:03
maybe you may send me files which you tested so i will be sure that problems not in files

**Comment by Munoon** [comment] 2018-10-30 12:17
Can you help me with that also?
![image](https://user-images.githubusercontent.com/43534008/47717260-f96c0a80-dc4d-11e8-9771-f22de47db020.png)
That russian nicknames. But if i go to there profiles everything good:
![image](https://user-images.githubusercontent.com/43534008/47717391-5071df80-dc4e-11e8-9e1d-b19692062caf.png)

**Comment by Munoon** [comment] 2018-10-30 18:37
im tried to reinstall your code on localhost but it still didnt work..

**Comment by Munoon** [comment] 2018-10-31 13:39
all intresting info what i have:
hosting: beget.ru
main csm: wordpress
php version: 7.1.1
operation system: linux
error logs from AWStats: 
![image](https://user-images.githubusercontent.com/43534008/47791811-3229e380-dd23-11e8-9cbe-335a102e3a69.png)

**Comment by kennyLtv** [comment] 2018-10-31 14:20
None of that information really helps us determine the problem you are having. Please be sure the software has not created an error_log in any of its directories/sub-directories. We can't determine a remedy for your problem if we don't know what the problem is.

**Comment by kennyLtv** [comment] 2018-10-31 14:22
Well, I guess the PHP version I asked for does a little as I believe we developed this on php 7.1 or 7.0 so in terms of PHP version you should be ok.

**Comment by Munoon** [comment] 2018-10-31 15:42
Maybe I can give you acces and try to fix it by yourself?

**Comment by kennyLtv** [comment] 2018-11-01 15:44
I don't access other peoples systems. It's something I have never done and don't intend to as I don't want to be blamed for anything should something happen. It's just easier for me not to have to worry about it. If you are unable to make the system give you any sort of actual error other than it telling you there is an error there is nothing I can do to help you. Please check your install location's subdirectories to be sure it wasn't generated else where. 

In the meantime, I am closing this issue as there is nothing I can do to help you.

**Closed by kennyLtv** 2018-11-01 15:44 UTC
